language: ruby
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.16.3
services:
  - postgresql
before_script:
  - psql -c 'create user "parkett" with superuser password '\''parkett'\'';' -U postgres
  - psql -c 'create database "parkett";' -U postgres
  - psql -c 'create database "parkett-test";' -U postgres
