language: ruby
rvm:
  - 2.6.3
before_install: gem install bundler -v 1.17.2
services:
  - postgresql
before_script:
  - psql -c 'create user "parkett" with superuser password '\''parkett'\'';' -U postgres
  - psql -c 'create database "parkett";' -U postgres
  - psql -c 'create database "parkett-test";' -U postgres
